merged in new packages.txt gen script

diff --git a/FAQ b/FAQ
--- a/FAQ
+++ b/FAQ
@@ -284,116 +284,71 @@ Frequenty Asked Questions:
  The PACKAGES.TXT can be generated by the following script:
 
  ### BEGIN SCRIPT
-        #!/bin/sh
-        base_dir=`pwd`
-        file_target=PACKAGES.TXT
-        target=$base_dir/$file_target.tmp
-        final_target=$base_dir/$file_target
-        debugger=0
-          ## initialize over size count for compressed and uncompressed
-          totalcomp_k=0
-          totaluncomp_k=0
-        
-        for ini_dir_struct in `find . | grep -m1 '\.tgz$'`
-                do
-        ## Path from script location to package, not including package
-        ini_location=`echo $ini_dir_struct |\
-        sed -re "s/([a-zA-Z0-9._\/-]+\/)([a-zA-Z0-9.+_-]+)-([a-zA-Z0-9._-]+).tgz/\1/"`
-        
-        ### Build Header for file
-        echo "$file_target              `date`" > $target
-        echo "" >> $target
-        echo "This file provides details on the Slackware packages found " >> $target
-        echo "in the ./ directory. " >> $target
-        echo "" >> $target
-        echo "Total size of all packages (compressed):  ZXaXZ MB " >> $target
-        echo "Total size of all packages (uncompressed): ZXbXZ MB" >> $target
-        	done
-        
-        
-        for dir_struct in `find . | grep '\.tgz$'` 
-        do
-        
-        	## File Name (xxxx-n.n.nbeta1-pre.tgz)
-        #	name_o_file=`echo $dir_struct |\
-        #		sed -re "s/([a-zA-Z0-9-\+_i.]+)*\///g"`
-        name_o_file=`echo $dir_struct |sed -re "s/([a-zA-Z0-9._\/-]+\/)/\2/"`
-        
-        	## Base File Name, no version number (xxxx)
-        	base_name=`echo $dir_struct |\
-        		sed -re "s/([a-zA-Z0-9._\/-]+\/)([a-zA-Z0-9+_-]+)-([a-zA-Z0-9._-]+).tgz/\2/"`
-        
-        	## Path from script location to package, not including package
-        	location=`echo $dir_struct |\
-        		sed -re "s/([a-zA-Z0-9._\/-]+\/)([a-zA-Z0-9+_-]+)-([a-zA-Z0-9._-]+).tgz/\1/"`
-        
-        	## Size of file in KB
-        	compressed=`gunzip -l $dir_struct | grep -v compress | awk '{print $1 }'`
-        	uncompressed=`gunzip -l $dir_struct | grep -v compress | awk '{print $2 }'`
-        	comp_k=`echo "${compressed}/1024" | bc`
-        	uncomp_k=`echo "${uncompressed}/1024" | bc`
-        	totalcomp_k=`expr $totalcomp_k + $comp_k`
-        	totaluncomp_k=`expr $totaluncomp_k + $uncomp_k`
-        
-        	## Contents of slack-required
-        	required=`tar ztf $dir_struct  | grep "slack-required" |\
-        		xargs -r -i"XFILEZ" tar xzf $dir_struct  -O XFILEZ |\
-        		xargs -r | sed "s/ /,/g"`
-        
-        	if [ $debugger -eq 1 ]; then
-        	## Debug output to $target
-        	echo "" >> $target
-        	echo "dir_struct = $dir_struct" >> $target
-        	echo "location = $location" >> $target
-        	echo "name_o_file = $name_o_file" >> $target
-        	echo "target = $target" >> $target
-        	echo "base_dir = $base_dir" >> $target
-        	echo "base_name = $base_name" >> $target
-        	echo "total compressed size in KB = $totalcomp_k" >> $target
-        	echo "total uncompressed size in KB = $totaluncomp_k" >> $target
-        	echo "tar zxf $dir_struct -O install/slack-desc | grep ^${base_name}:" >> $target
-        	 echo "" >> $target
-        	fi
-        
-        
-        	## Build PACKAGES.TXT
-        
-        	echo "" >> $target
-        	echo "PACKAGE NAME:  $name_o_file" >> $target
-        	echo "PACKAGE LOCATION:  $location" >> $target
-        	echo "PACKAGE SIZE (compressed):  $comp_k K" >> $target
-        	echo "PACKAGE SIZE (uncompressed):  $uncomp_k K" >> $target
-        	echo "PACKAGE REQUIRED: $required" >> $target
-        	echo "PACKAGE DESCRIPTION: " >> $target
-        		tar ztf $dir_struct  | grep "slack-desc" |\
-        		xargs -r -i"XFILEZ" tar xzf $dir_struct  -O XFILEZ |\
-        		grep "^${base_name}:"  >> $target
-        		
-        	#tar zxf $dir_struct -O install/slack-desc | grep "^${base_name}:"  >> $target
-        
-        
-        	## Count number of lines in desc... should be 11 (0+10)
-        	## Append to description
-        	        lines=`tar ztf $dir_struct  | grep "slack-desc" |\
-                        xargs -r -i"XFILEZ" tar xzf $dir_struct  -O XFILEZ |\
-                        grep "^${base_name}:" | wc -l`
-        	#lines=`tar zxf $dir_struct -O install/slack-desc | grep "^${base_name}:" | wc -l`
-        
-        		while [ ${lines} -le 10 ]
-        		do
-        			echo "${base_name}:" >> $target
-        			lines=`expr $lines + 1`
-        		done
-        
-        done
-        
-        ## calculate totals in MB
-        totalcomp_m=`expr $totalcomp_k / 1024`
-        totaluncomp_m=`expr $totaluncomp_k / 1024`
-        
-        cat $target | \
-        sed -e "s/ZXaXZ/$totalcomp_m/g" \
-        -e "s/ZXbXZ/$totaluncomp_m/g" > $final_target && rm $target
+    #!/bin/sh
+
+    function gen_packages_txt {
+	    echo '' > PACKAGES.TXT
+	    find . -type f -name '*.meta' -exec cat {} \; >> PACKAGES.TXT
+    }
+
+    function gen_md5_checksums {
+	    echo '' > CHECKSUMS.md5
+	    find . -type f -name '*.tgz' -exec md5sum {} \; >> CHECKSUMS.md5
+    }
+
+    function gen_meta {
+	    if [ ! -f $1 ]; then
+		    echo "File not found: $1"
+		    exit 1;
+	    fi
+	    NAME=$(echo $1|sed -re "s/([a-zA-Z0-9\/\.\-\+]+\/)(.*.tgz)$/\2/")
+	    LOCATION=$(echo $1|sed -re "s/([a-zA-Z0-9\/\.\-\+]+\/)(.*.tgz)$/\1/")
+	    SIZE=$( expr `gunzip -l $1 |tail -1|awk '{print $1}'` / 1024 )
+	    USIZE=$( expr `gunzip -l $1 |tail -1|awk '{print $2}'` / 1024 )
+	    REQUIRED=$(tar xzf $1 install/slack-required -O|xargs -iZ echo -n "Z,"|sed -e "s/,$//")
+	    METAFILE=$(echo $NAME|sed -re "s/\.tgz$/\.meta/")
+	    echo "PACKAGE NAME:  $1" > $LOCATION/$METAFILE
+	    echo "PACKAGE LOCATION:  $NAME" >> $LOCATION/$METAFILE
+	    echo "PACKAGE SIZE (compressed):  $SIZE K" >> $LOCATION/$METAFILE
+	    echo "PACKAGE SIZE (uncompressed):  $USIZE K" >> $LOCATION/$METAFILE
+	    echo "PACKAGE REQUIRED:  $REQUIRED" >> $LOCATION/$METAFILE
+	    echo "PACKAGE DESCRIPTION:" >> $LOCATION/$METAFILE
+	    tar xzf $1 install/slack-desc -O|grep -E '\w+\:'|grep -v '^#' >> $LOCATION/$METAFILE
+	    echo "" >> $LOCATION/$METAFILE
+    }
+
+    case "$1" in
+	    pkg)
+		    if [ -n "$2" ]; then
+			    gen_meta $2
+		    else
+			    echo "$0 [pkg [file]|all|PACKAGESTXT|MD5]"
+		    fi
+	    ;;
+	    all)
+		    for pkg in `find . -type f -name '*.tgz' -print`
+		    do
+			    gen_meta $pkg
+		    done
+	    ;;
+	    new)
+		    for pkg in `find . -type f -name '*.tgz' -print`
+		    do
+			    if [ ! -f "`echo $pkg|sed -re 's/\.tgz$/\.meta/'`" ]; then
+				    gen_meta $pkg
+			    fi
+		    done
+	    ;;
+	    PACKAGESTXT)
+		    gen_packages_txt
+	    ;;
+	    MD5)
+		    gen_md5_checksums
+	    ;;
+	    *)
+		    echo "$0 [pkg [file]|all|PACKAGESTXT|MD5]"
+	    ;;
+    esac
  ### END SCRIPT
 
 18. How can I download every package in a disk set?
@@ -433,8 +388,8 @@ Frequenty Asked Questions:
  An example slack-required file is present within the slapt-get slack package.
 
  This data will then need to be extracted when the mirror's PACKAGES.TXT file
- is generated.  See FAQ #17 for a user contributed example of how to generate
- the PACKAGES.TXT file.  The following is an example entry
+ is generated.  See FAQ #17 for an example of how to generate the
+ PACKAGES.TXT file.  The following is an example entry:
 
     PACKAGE NAME:  man-pages-1.56-noarch-1.tgz
     ...(snip)
