updated dep script in FAQ

diff --git a/FAQ b/FAQ
--- a/FAQ
+++ b/FAQ
@@ -596,6 +596,7 @@ Frequenty Asked Questions:
  			if [ -f ${MF}.bz2 ]; then bunzip2 -c ${MF}.bz2 >> ${MF}; rm ${MF}.bz2; fi
  		fi
  	done
+	if [ ! -f ${MF} ]; then echo "Failed to download MANIFEST"; exit 1; fi
  	echo "extracting package data"
  	grep -n ' Package\: ' ${MF}|awk '{print $1 $3}'|sed -re "s/\|//g" > ${PKGLINES}
  }
@@ -655,7 +656,7 @@ Frequenty Asked Questions:
  if [ -z "$1" ]; then echo "Usage: $0 [--update|packages]"; exit; fi
  # get package cache data if it is not already there, or we want it
  cd ${WORKINGDIR}
- if [ "$1" == "--update" ]; then shift; get_pkg_cache_data; fi
+ if [ "$1" == "--update" ]; then get_pkg_cache_data; exit; fi
  if [ ! -f ${PKGLINES} ]; then get_pkg_cache_data; fi
  # read pkg data into memory 
  while read line;do DEPDATA[${DEPDATACOUNT}]=$line; DEPDATACOUNT=$((DEPDATACOUNT + 1)); done < ${PKGLINES}
